### ISSUE TITLE
Fail with 'IllegalArgumentException: Value out of range for int'

### ISSUE THREAD

**Issue by nicokosi** [nicokosi/strava-activity-graphs#3]
I cannot generate graphs with my personal data, `strava-activity-graphs` fails with this stack trace:
```sh
$> lein run $STRAVA_TOKEN
Strava API token provided
Exception in thread "main" java.lang.IllegalArgumentException: Value out of range for int: 1519567572000, compiling:(/private/var/folders/vn/t_jql4vn7fzb9cr0qxcxdqlm0000gn/T/form-init15257232092407381370.clj:1:126)
	at clojure.lang.Compiler.load(Compiler.java:7526)
	at clojure.lang.Compiler.loadFile(Compiler.java:7452)
	at clojure.main$load_script.invokeStatic(main.clj:278)
	at clojure.main$init_opt.invokeStatic(main.clj:280)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invokeStatic(main.clj:311)
	at clojure.main$null_opt.invokeStatic(main.clj:345)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
Caused by: java.lang.IllegalArgumentException: Value out of range for int: 1519567572000
	at clojure.lang.RT.intCast(RT.java:1241)
	at clojure.lang.RT.intCast(RT.java:1211)
	at incanter.core$get_column_id.invokeStatic(core.clj:1232)
	at incanter.core$get_column_id.invoke(core.clj:1214)
	at incanter.core$eval7122$fn__7124$fn__7130$fn__7131.invoke(core.clj:1398)
	at clojure.core$map$fn__5587.invoke(core.clj:2745)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:528)
	at clojure.core$seq__5124.invokeStatic(core.clj:137)
	at clojure.core$concat$fn__5215.invoke(core.clj:717)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:528)
	at clojure.core$seq__5124.invokeStatic(core.clj:137)
	at clojure.core$concat$cat__5217$fn__5218.invoke(core.clj:726)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:528)
	at clojure.core$seq__5124.invokeStatic(core.clj:137)
	at clojure.core$map$fn__5591.invoke(core.clj:2749)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:528)
	at clojure.core$seq__5124.invokeStatic(core.clj:137)
	at clojure.core$dorun.invokeStatic(core.clj:3125)
	at clojure.core$dorun.invoke(core.clj:3125)
	at incanter.charts$eval9445$fn__9446.doInvoke(charts.clj:564)
	at clojure.lang.RestFn.invoke(RestFn.java:573)
	at clojure.lang.MultiFn.invoke(MultiFn.java:271)
	at clojure.lang.AFn.applyToHelper(AFn.java:186)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:657)
	at clojure.core$apply.invoke(core.clj:652)
	at incanter.charts$create_xy_series_plot$fn__9575.invoke(charts.clj:1190)
	at incanter.charts$create_xy_series_plot.invokeStatic(charts.clj:1189)
	at incanter.charts$create_xy_series_plot.doInvoke(charts.clj:1131)
	at clojure.lang.RestFn.applyTo(RestFn.java:146)
	at clojure.core$apply.invokeStatic(core.clj:663)
	at clojure.core$apply.invoke(core.clj:652)
	at incanter.charts$time_series_plot_STAR_.invokeStatic(charts.clj:1367)
	at incanter.charts$time_series_plot_STAR_.doInvoke(charts.clj:1366)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.core$apply.doInvoke(core.clj:652)
	at clojure.lang.RestFn.invoke(RestFn.java:660)
	at strava_activity_graphs.core$ts_plot.invokeStatic(core.clj:30)
	at strava_activity_graphs.core$ts_plot.doInvoke(core.clj:28)
	at clojure.lang.RestFn.invoke(RestFn.java:826)
	at strava_activity_graphs.core$display_charts.invokeStatic(core.clj:47)
	at strava_activity_graphs.core$display_charts.invoke(core.clj:40)
	at strava_activity_graphs.core$_main.invokeStatic(core.clj:81)
	at strava_activity_graphs.core$_main.doInvoke(core.clj:76)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.lang.Var.invoke(Var.java:381)
	at user$eval149.invokeStatic(form-init15257232092407381370.clj:1)
	at user$eval149.invoke(form-init15257232092407381370.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7052)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	... 12 more
```

**Comment by nicokosi** [comment]
Fixed in cd750d3aaccf6a1606782520e5512ac0840aff4f! 🎉
